// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

int incrementCounter() =>
    RustLib.instance.api.crateApiCounterIncrementCounter();

int decrementCounter() =>
    RustLib.instance.api.crateApiCounterDecrementCounter();

int getCounter() => RustLib.instance.api.crateApiCounterGetCounter();
